/* Builds js/icons.js by embedding the exact SVG path data from lucide-static.
   Run: node scripts/embed-icons.js */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ICONS_DIR = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const OUT = path.join(__dirname, '..', 'js', 'icons.js');

// [exported key, lucide file name]
const ICONS = [
  ['home', 'house'],
  ['calendar', 'calendar'],
  ['calendarDays', 'calendar-days'],
  ['bookOpen', 'book-open'],
  ['wallet', 'wallet'],
  ['dumbbell', 'dumbbell'],
  ['settings', 'settings'],
  ['plus', 'plus'],
  ['minus', 'minus'],
  ['x', 'x'],
  ['check', 'check'],
  ['checkCircle', 'circle-check'],
  ['circle', 'circle'],
  ['trash', 'trash-2'],
  ['pencil', 'pencil'],
  ['chevronLeft', 'chevron-left'],
  ['chevronRight', 'chevron-right'],
  ['chevronDown', 'chevron-down'],
  ['arrowUp', 'arrow-up'],
  ['arrowDown', 'arrow-down'],
  ['arrowUpRight', 'arrow-up-right'],
  ['arrowLeftRight', 'arrow-left-right'],
  ['moreHorizontal', 'ellipsis'],
  ['bell', 'bell'],
  ['bellOff', 'bell-off'],
  ['bellRing', 'bell-ring'],
  ['clock', 'clock'],
  ['alertTriangle', 'triangle-alert'],
  ['alertCircle', 'circle-alert'],
  ['info', 'info'],
  ['sparkles', 'sparkles'],
  ['moon', 'moon'],
  ['sun', 'sun'],
  ['monitor', 'monitor'],
  ['download', 'download'],
  ['upload', 'upload'],
  ['save', 'save'],
  ['fileDown', 'file-down'],
  ['fileUp', 'file-up'],
  ['database', 'database'],
  ['copy', 'copy'],
  ['banknote', 'banknote'],
  ['creditCard', 'credit-card'],
  ['smartphone', 'smartphone'],
  ['trendingUp', 'trending-up'],
  ['trendingDown', 'trending-down'],
  ['target', 'target'],
  ['scale', 'scale'],
  ['flag', 'flag'],
  ['listTodo', 'list-todo'],
  ['search', 'search'],
  ['repeat', 'repeat'],
  ['delete', 'delete'],
  ['equal', 'equal'],
  ['users', 'users'],
  ['graduationCap', 'graduation-cap'],
  ['tag', 'tag'],
  ['inbox', 'inbox'],
  ['undo2', 'undo-2'],
  ['redo2', 'redo-2'],
  ['checkCheck', 'check-check'],
  ['filter', 'filter'],
  ['badgeCheck', 'badge-check'],
  ['zap', 'zap'],
  ['stickyNote', 'sticky-note'],
  ['pin', 'pin'],
];

function extractBody(svg) {
  const start = svg.indexOf('>', svg.indexOf('<svg')) + 1;
  const end = svg.lastIndexOf('</svg>');
  return svg.slice(start, end).replace(/\s+/g, ' ').trim();
}

const entries = [];
for (const [key, file] of ICONS) {
  const fp = path.join(ICONS_DIR, file + '.svg');
  if (!fs.existsSync(fp)) {
    console.error('Missing icon file: ' + file);
    process.exit(1);
  }
  const body = extractBody(fs.readFileSync(fp, 'utf8'));
  entries.push(`  ${key}: '${body.replace(/'/g, "\\'")}'`);
}

const out = `/* ZLife icons
   Embedded SVG path data from lucide-static v0.468.0 (ISC license).
   Generated by scripts/embed-icons.js — do not edit by hand. */

export const ICONS = {
${entries.join(',\n')}
};

let fallback = '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>';

export function icon(name, cls) {
  const body = ICONS[name] || fallback;
  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" ' +
    'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"' +
    (cls ? ' class="' + cls + '"' : '') + ' aria-hidden="true">' + body + '</svg>';
}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, 'utf8');
console.log('Wrote js/icons.js with ' + entries.length + ' icons');